services:
  - type: web
    name: quickquote
    env: node
    buildCommand: mkdir -p uploads/videos && mkdir -p data && npm install && npm run build
    startCommand: npm run start-prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    disk:
      name: data
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
